
name: google-chat-job-failed
description: Sends messages to google chat when a job fails
author: datamole-ai
branding:
  icon: 'bell'
  color: 'green'

inputs:
  json:
    description: 'list of job objects'
    required: true
    default: ''
  gchatURL:
    description: 'google chat webhook'
    required: true
    default: ''
runs:
  using: "composite"
  
  steps:
  - shell: bash
    env:
      NEEDS_CONTEXT: ${{ inputs.json }}
      GOOGLE_CHAT_WEBHOOK: ${{ inputs.gchatURL }}

    run: |
      export GITHUB_LINK=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID
      export HEAD=$(echo ${GITHUB_REF##*/})
      export REPO_NAME=$(echo ${GITHUB_REPOSITORY#*/})
      python ${{ github.action_path }}/action.py
      
     