
name: google-chat-job-failed
description: Sends messages to google chat when a job fails
author: datamole-ai
branding:
  icon: 'bell'
  color: 'green'

inputs:
  json:
    description: 'list of job objects'
    required: true
    default: ''
  gchatURL:
    description: 'google chat webhook'
    required: true
    default: ''
  initiator:
    description: 'The user that should be mentioned in the message'
    required: false
runs:
  using: "composite"
  
  steps:
  - shell: bash
    env:
      NEEDS_CONTEXT: ${{ inputs.json }}
      GOOGLE_CHAT_WEBHOOK: ${{ inputs.gchatURL }}
      INITIATOR: ${{ inputs.initiator }}
    
    run: |
      GITHUB_LINK=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID
      HEAD=$(echo ${GITHUB_REF##*/})
      REPO_NAME=$(echo ${GITHUB_REPOSITORY#*/})
      failed_list=()
      
      # Turn JSON list to bash array
      list=( $(echo $NEEDS_CONTEXT | jq 'keys' | sed -e 's/\[ //g' -e 's/\ ]//g' -e 's/\,//g' | tr -d '"') ) 

      # Iterate through array, append $failed_list with job names that failed
      for job in ${list[@]}
        do
          job_status=$(echo $NEEDS_CONTEXT | jq  --arg j "$job" '.[$j]' | jq .'result' | tr -d '"')
          [[ "$job_status" == 'failure' ]] && \
            failed_list+=( "$job" )
        done
      
      # Do nothing if no failed jobs.
      [[ ${#failed_list[@]} -eq 0 ]] && exit 0
      echo ${failed_list[@]}
      # Format list: replace spaces with <br>
      failed_list=$(echo ${failed_list[@]} | sed -e 's/ /<br>/g')
      echo $failed_list

      text="Failed jobs:<br><b>$failed_list</b>"
      
      # Build JSON message
      message=$( jq -n \
                        --arg fl "$failed_list" \
                        --arg initiator "$INITIATOR" \
                        --arg txt "$text" \
                        --arg repo "$REPO_NAME:$HEAD" \
                        --arg gl "$GITHUB_LINK"\
                        --arg ref "on branch $HEAD" \
                        '{"cards":[{"header":{"title":"<b>JOBS FAILED</b>","subtitle":$repo},"sections":[{"widgets":[{"textParagraph":{"text":$initiator}},{"textParagraph":{"text":$txt}},{"buttons":[{"textButton":{"text":"VIEW RUN","onClick":{"openLink":{"url":$gl}}}}]}]}]}]}' )
      
      # Send message to google chat
      curl -i \
        -H 'Content-Type: application/json' -d "$message" \
        -X POST "$GOOGLE_CHAT_WEBHOOK"
